##############
## DATABASE ##
##############
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: ${PGADMIN_RBRANAS_USER}
    password: ${PGADMIN_RBRANAS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true