##############
## DATABASE ##
##############
spring:
  flyway:
    locations: classpath:db/migration/test
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:account_backend;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  logging:
    level:
      org.springframework.boot: DEBUG
      org.flywaydb.core: DEBUG
  h2:
    console:
      enabled: true
      path: /h2