##############
## DATABASE ##
##############
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:adm_ride_test;mode=PostgreSQL;database_to_lower=TRUE
  h2:
    console:
      enabled: true
      path: /h2
